apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crispy-com
spec:
  dnsNames:
  - crispy.com
  issuerRef:
    name: letsencrypt-clusterissuer
    kind: ClusterIssuer
  secretName: crispy-com-tls