apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: helbk@protonmail.com
    privateKeySecretRef:
      name: letsencrypt-clusterissuer-key
    solvers:
    - http01:
       ingress:
         class: nginx