apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crispy-com
spec:
  dnsNames:
  - crispy.com
  commonName: crispy.com
  secretName: crispy-com-tls
  issuerRef:
    name: vault-issuer