apiVersion: v1
kind: Service
metadata:
  name: crispy
  labels:
    app: crispy
spec:
  selector:
    app: crispy
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.containerPort }}