- name: Install Docker
  hosts: EC2
  become: true
  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_cache: true
  - name: Install Docker
    yum:
      name: docker
      state: latest
  - name: Start Docker as a service
    systemd:
      name: docker
      state: started
  - name: Add ec2-user to Docker group
    user:
      name: ec2-user
      groups: docker
  - name: Install pip
    yum:
      name: python-pip
      state: latest
  - name: Install Docker SDK
    pip:
      name: docker

- name: Deploy Docker image
  hosts: EC2
  tasks:
  - name: Log in to DockerHub
    community.docker.docker_login:
      username: elabrom
      password: rekcod
  - name: Start a Docker container
    community.docker.docker_container:
      name: crispy
      state: started
      image: elabrom/crispy
      pull: true # Always pull the latest image
      container_default_behavior: no_defaults
      ports:
        - 8080:8080
  - name: Log out of DockerHub
    community.docker.docker_login:
      state: absent