- name: Install Docker
  hosts: EC2
  become: true
  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_cache: true
  - name: Install Docker
    yum:
      name: docker
      state: latest
  - name: Start Docker as a service
    systemd:
      name: docker
      state: started
  - name: Add ec2-user to Docker group
    user:
      name: ec2-user
      groups: docker