name: Build and push to Docker registry

on:
  push:
    branches: [ feature ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test Go
        run: go test -v      
      
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: elabrom/crispy
          tags: latest